# Generated by Django 5.0.1 on 2024-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieshows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movieshows/images')),
            ],
        ),
    ]
